name: Publish OpenAI CLI
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Source
        id: source
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Validate tag
        run: |
          if [[ ${{ steps.source.outputs.SOURCE_TAG }} == "" ]]; then
            echo "This workflow can only be triggered by a tag."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish
        run: yarn nx run cli:publish
        env:
          VERSION: ${{ steps.source.outputs.SOURCE_TAG }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
