name: Publish OpenAI CLI
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check tag
        id: check_tag
        run: |
          if [[ ${{ github.ref }} != "refs/tags/"* ]]; then
            echo "This workflow can only be triggered by a tag." >&2
            exit 1
          fi

      - name: Source
        id: source
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Validate tag
        run: |
          if [[ ${{ steps.source.outputs.SOURCE_TAG }} == "" ]]; then
            echo "This workflow can only be triggered by a tag."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish
        run: yarn nx run cli:publish
        env:
          VERSION: ${{ steps.source.outputs.SOURCE_TAG }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
